SET DEFINE OFF

INSERT INTO DEPARTMENTS
(DEP_ID,DEP_NAME,DEP_LOCATION) VALUES (1,'Management','London');

INSERT INTO DEPARTMENTS
(DEP_ID,DEP_NAME,DEP_LOCATION) VALUES (2,'Engineering','Cardiff');

INSERT INTO DEPARTMENTS
(DEP_ID,DEP_NAME,DEP_LOCATION) VALUES (3,'Research & Development','Edinburgh');

INSERT INTO DEPARTMENTS
(DEP_ID,DEP_NAME,DEP_LOCATION) VALUES (4,'Sales','Belfast');

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90001,'John Smith','CEO','',TO_DATE('01/01/95','DD/MM/RR'),100000,1
);

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90002,'Jimmy Willis','Manager',90001,TO_DATE('23/09/03','DD/MM/RR'),52500,4
);

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90003,'Roxy Jones','Salesperson','',TO_DATE('11/02/17','DD/MM/RR'),35000,4
);

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90004,'Selwyn Field','Salesperson','',TO_DATE('20/05/15','DD/MM/RR'),32000,4
);

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90005,'David Hallett','Engineer',90006,TO_DATE('17/04/18','DD/MM/RR'),40000,2
);

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90006,'Sarah Phelps','Manager',90001,TO_DATE('21/03/15','DD/MM/RR'),45000,2
);

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90007,'Louise Harper','Engineer',90006,TO_DATE('01/01/13','DD/MM/RR'),47000,2
);

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90008,'Tina Hart','Engineer',90009,TO_DATE('28/07/14','DD/MM/RR'),45000,3
);

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90009,'Gus Jones','Manager',90001,TO_DATE('15/05/18','DD/MM/RR'),50000,3
);

INSERT INTO EMPLOYEES
(
EMP_ID,EMP_NAME,EMP_JOB_TITLE,EMP_MANAGER_ID,EMP_DATE_HIRED,EMP_SALARY,EMP_DEP_ID
) VALUES 
(
90010,'Mildred Hall','Secretary',90001,TO_DATE('12/10/96','DD/MM/RR'),35000,1
);
